[[redirects]]
  from = "/api/auth/*"
  to = "https://taskease-backend.onrender.com/api/auth/:splat"
  status = 200
  force = false
  headers = {Access-Control-Allow-Origin = "https://razz-dev.netlify.app", Access-Control-Allow-Credentials = "true"}

[[redirects]]
  from = "/api/tasks/*"
  to = "https://taskease-backend.onrender.com/api/tasks/:splat"
  status = 200
  force = false
  headers = {Access-Control-Allow-Origin = "https://razz-dev.netlify.app", Access-Control-Allow-Credentials = "true"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://razz-dev.netlify.app"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
